version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
      docker: 18
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo installing libraries...
      - pip install -r requirements.txt
      - echo running unit tests...
      - python -m pytest tests/tests.py
      - echo pulling files from s3...
      - aws s3 cp s3://insert-s3-bucket-name/index/index.html .
      - aws s3 cp s3://insert-s3-bucket-name/distributions . --recursive
      - echo building new package distribution...
      - python setup.py sdist
      - export PACKAGE_VERSION=`python -c "import ds_helpers; print(ds_helpers.__version__)"`
      - echo updating index.html
      - echo "<a href="insert_package_name-$PACKAGE_VERSION.tar.gz">
        insert_package_name-$PACKAGE_VERSION.tar.gz
        </a>
        <br>" >> templates/index.html
      - echo uploading new artifacts to s3...
      - aws s3 cp dist/insert-s3-bucket-name-$PACKAGE_VERSION.tar.gz s3://insert-s3-bucket-name/distributions/
      - aws s3 cp templates/index.html s3://insert-s3-bucket-name/index/index.html
      - echo logging into ecr...
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - REPOSITORY_URI=INSERT_ECR_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo building docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo pushing docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"python-library","imageUri":"%s"}]' $REPOSITORY_URI:latest > taskdefinition.json
artifacts:
  files:
    - '**/*'
  base_directory: base_location
  name: build-artifacts
  discard-paths: no
